#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${VELACLAW_INSTALL_E2E_IMAGE:-velaclaw-install-e2e:local}"
INSTALL_URL="${VELACLAW_INSTALL_URL:-https://velaclaw.bot/install.sh}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
VELACLAW_E2E_MODELS="${VELACLAW_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker"

echo "==> Run E2E installer test"
docker run --rm \
  -e VELACLAW_INSTALL_URL="$INSTALL_URL" \
  -e VELACLAW_INSTALL_TAG="${VELACLAW_INSTALL_TAG:-latest}" \
  -e VELACLAW_E2E_MODELS="$VELACLAW_E2E_MODELS" \
  -e VELACLAW_INSTALL_E2E_PREVIOUS="${VELACLAW_INSTALL_E2E_PREVIOUS:-}" \
  -e VELACLAW_INSTALL_E2E_SKIP_PREVIOUS="${VELACLAW_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e VELACLAW_NO_ONBOARD=1 \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
