export const browserCoreExamples = [
  "velaclaw browser status",
  "velaclaw browser start",
  "velaclaw browser stop",
  "velaclaw browser tabs",
  "velaclaw browser open https://example.com",
  "velaclaw browser focus abcd1234",
  "velaclaw browser close abcd1234",
  "velaclaw browser screenshot",
  "velaclaw browser screenshot --full-page",
  "velaclaw browser screenshot --ref 12",
  "velaclaw browser snapshot",
  "velaclaw browser snapshot --format aria --limit 200",
  "velaclaw browser snapshot --efficient",
  "velaclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "velaclaw browser navigate https://example.com",
  "velaclaw browser resize 1280 720",
  "velaclaw browser click 12 --double",
  'velaclaw browser type 23 "hello" --submit',
  "velaclaw browser press Enter",
  "velaclaw browser hover 44",
  "velaclaw browser drag 10 11",
  "velaclaw browser select 9 OptionA OptionB",
  "velaclaw browser upload /tmp/velaclaw/uploads/file.pdf",
  'velaclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "velaclaw browser dialog --accept",
  'velaclaw browser wait --text "Done"',
  "velaclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "velaclaw browser console --level error",
  "velaclaw browser pdf",
];
